"""Chunk 2.2: generate the N64Recomp config (wg3d.us.toml) and run the recompiler.

Inputs come from earlier chunks so nothing is hand-copied:
  syms/wg3d.us.syms.toml        function list (1.6)
  syms/dead_ignore.txt          dead library code to ignore (1.3/1.8, tools/gen_libsyms.py)
  tools/hw_audit.py DECISIONS   functions to stub (2.1; currently none)
  tools/find_spinloops.py       busy-wait loops that get a yield hook (3.3; SPIN_FLAGS below)

After recompiling it writes include/wg3d_skipped.h (chunk 2.3): declarations for the skipped
functions the generated code calls that funcs.h doesn't declare (N64Recomp declares reimplemented
functions only). Each must be an N64Recomp-skipped function; anything else is an error.

Usage: python tools/gen_config.py [--trace] [--no-run] [--no-check]
  --trace     enable N64Recomp trace_mode (adds trace.h calls to every function); writes
              wg3d.us.trace.toml -> RecompiledFuncsTrace/ instead of the normal config/output
  --no-run    only write the config
  --no-check  skip the clang-cl syntax check of the generated C
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from find_spinloops import find_loops  # noqa: E402
from gen_libsyms import list_from_cpp, runtime_funcs  # noqa: E402
from hw_audit import DECISIONS  # noqa: E402
from rom_map import TEXT_START  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "wg3d.us.toml"
OUTPUT_DIR = "RecompiledFuncs"
DECLS_HEADER = ROOT / "include" / "wg3d_skipped.h"
# Skipped functions with live callers that the runtime doesn't implement yet (Phase 3).
PHASE3_GAPS = {"osPiRawReadIo"}
VCVARS = r"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
# Generated-code noise only (same classes the reference projects silence). Implicit declarations stay on.
NOISE_FLAGS = "-Wno-unused-variable -Wno-unused-label -Wno-unused-but-set-variable"
# Busy-wait loops (tools/find_spinloops.py, docs/spinloops.md) rely on N64 preemption; ultramodern
# switches threads only inside OS calls, so each loop gets a wg3d_spin_yield() hook (yield_self_1ms) at its head.
# Every polled flag must be listed here with who releases it; an unlisted loop is an error.
SPIN_FLAGS = {
    0x8009F38C: "scheduler's count of gfx tasks in flight: +1 in func_80003898 when a gfx task is queued, "
                "-1 in func_8000392C (scheduler thread, on SP done)",
}
# The entry stub ends with `jr $t2` into boot_main (0x80003480).
EXPECTED_MESSAGES = {"[Info] Indirect tail call in recomp_entrypoint"}


def toml_list(items) -> str:
    if not items:
        return "[]"
    return "[\n" + "".join(f'    "{i}",\n' for i in items) + "]"


# Test hooks (chunk 4.6). The game seeds rand() (func_8000C97C, state 0x800A3470) once at startup from
# osGetTime() in its main thread: func_80047E5C, `jal srand_wrapper; move $a0, $v1` at 0x80047F50.
# wg3d_seed_override() replaces $v1 there when WG3D_FIXED_SEED is set (no-op otherwise), so test runs
# can be repeated with the same random sequence.
TEST_HOOKS = [
    ("func_80047E5C", 0x80047F50, "wg3d_seed_override(rdram, ctx); /* wg3d: WG3D_FIXED_SEED (chunk 4.6) */"),
]


def spin_hooks():
    loops, _ = find_loops()
    hooks, errors = [], []
    for func, branch, head, _, loads in loops:
        addrs = {ad for _, ad, _ in loads}
        if None in addrs or not addrs <= SPIN_FLAGS.keys():
            errors.append(f"{func}: polling loop at {head:08X} on {sorted(addrs, key=str)} not in SPIN_FLAGS")
            continue
        flags = ", ".join(f"{a:08X}" for a in sorted(addrs))
        hooks.append((func, head, f"wg3d_spin_yield(rdram); /* wg3d: busy-wait on {flags} (docs/spinloops.md) */"))
    if errors:
        raise SystemExit("\n".join(errors))
    return hooks


def write_config(trace: bool) -> None:
    ignored = [n for n in (ROOT / "syms" / "dead_ignore.txt").read_text().split() if n]
    stubs = sorted(f for f, (d, _) in DECISIONS.items() if d == "stub")
    flag_notes = "".join(f"#   {a:08X}: {why}\n" for a, why in sorted(SPIN_FLAGS.items()))
    hook_text = "".join(f'''
[[patches.hook]]
func = "{func}"
before_vram = 0x{head:08X}
text = "{text}"
''' for func, head, text in spin_hooks() + TEST_HOOKS)
    text = f"""# N64Recomp config for W.G. 3D Hockey (US V1.0). Generated by tools/gen_config.py; do not edit.
# Regenerate after changing syms, the dead-code list or hw_audit decisions.

[input]
entrypoint = 0x{TEXT_START:08X}
symbols_file_path = "syms/wg3d.us.syms.toml"
rom_file_path = "baserom.us.z64"
output_func_path = "{OUTPUT_DIR}"
# wg3d_skipped.h declares skipped functions that funcs.h doesn't (generated; include/).
# wg3d_patches.h declares runtime functions used by the hooks below (hand-written; include/).
recomp_include = "#include \\"recomp.h\\"\\n#include \\"wg3d_skipped.h\\"\\n#include \\"wg3d_patches.h\\""
# IDO -mips2 code uses FR=0 even/odd FPR pairs; no odd FPR is used as a double (docs/hw_audit.md).
uses_mips3_float_mode = false
trace_mode = {'true' if trace else 'false'}

[patches]
# Library functions that are dead after recompilation (only reachable through functions N64Recomp
# skips) but call skipped functions with no runtime implementation; ignoring them avoids link errors.
# Source: syms/dead_ignore.txt (docs/libultra_coverage.md, "Link-level gaps").
ignored = {toml_list(ignored)}

# No compiled function accesses hardware directly (docs/hw_audit.md), so nothing is stubbed or patched.
stubs = {toml_list(stubs)}

# Busy-wait loops get a yield at the loop head (chunk 3.3). Polled flags:
{flag_notes}{hook_text}"""
    CONFIG.write_text(text, encoding="utf-8")


def run_recompiler() -> int:
    out = ROOT / OUTPUT_DIR
    if out.exists():
        for f in out.glob("*"):
            f.unlink()
    r = subprocess.run([str(ROOT / "lib/N64Recomp/build/N64Recomp.exe"), CONFIG.name], cwd=ROOT,
                       capture_output=True, text=True)
    log = r.stdout + r.stderr
    (ROOT / "build" / "n64recomp.log").write_text(log)
    unexpected = [l.strip() for l in log.splitlines()
                  if l.strip() and not l.startswith(("Function count:", "Working dir:")) and l.strip() not in EXPECTED_MESSAGES]
    count = next((l for l in log.splitlines() if l.startswith("Function count:")), "")
    files = sorted(out.glob("*.c"))
    print(f"N64Recomp exit {r.returncode}; {count}; {len(files)} C files in {OUTPUT_DIR}/")
    for l in unexpected:
        print(f"  unexpected: {l}")
    return 0 if r.returncode == 0 and not unexpected else 1


def write_decls() -> int:
    out = ROOT / OUTPUT_DIR
    declared = set(re.findall(r"^void (\w+)\(uint8_t\* rdram, recomp_context\* ctx\);", (out / "funcs.h").read_text(), re.M))
    called, defined = set(), set()
    for f in out.glob("funcs_*.c"):
        text = f.read_text()
        called |= set(re.findall(r"\b(\w+)\(rdram, ctx\)", text))
        defined |= set(re.findall(r"^RECOMP_FUNC void (\w+)\(", text, re.M))
    # Hook targets are declared in the hand-written include/wg3d_patches.h (also in recomp_include).
    patch_decls = set(re.findall(r"^void (\w+)\(", (ROOT / "include" / "wg3d_patches.h").read_text(), re.M))
    missing = sorted(called - declared - defined - patch_decls - {"LOOKUP_FUNC"})
    sl = ROOT / "lib/N64Recomp/src/symbol_lists.cpp"
    skipped = list_from_cpp(sl, "reimplemented_funcs") | list_from_cpp(sl, "ignored_funcs")
    runtime = runtime_funcs()
    errors = []
    lines = ["// Generated by tools/gen_config.py (chunk 2.3); do not edit.",
             "// Declarations for N64Recomp-skipped functions that the generated code calls but funcs.h",
             "// does not declare. Each is implemented by the runtime (librecomp/ultramodern) or, for the",
             "// Phase 3 gaps, by this project.",
             "#ifndef WG3D_SKIPPED_H", "#define WG3D_SKIPPED_H", "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    for name in missing:
        base = name[:-len("_recomp")] if name.endswith("_recomp") else None
        if base is None or base not in skipped:
            errors.append(f"generated code calls undeclared {name}, which is not an N64Recomp-skipped function")
            continue
        if base in runtime:
            note = "runtime"
        elif base in PHASE3_GAPS:
            note = "PHASE 3: not in the runtime yet"
        else:
            errors.append(f"{name}: skipped, called, but neither in the runtime nor a known Phase 3 gap")
            note = "MISSING"
        lines.append(f"void {name}(uint8_t* rdram, recomp_context* ctx); // {note}")
    lines += ["", "#ifdef __cplusplus", "}", "#endif", "", "#endif", ""]
    DECLS_HEADER.parent.mkdir(exist_ok=True)
    DECLS_HEADER.write_text("\n".join(lines))
    print(f"wrote {DECLS_HEADER.relative_to(ROOT)}: " + ", ".join(missing))
    for e in errors:
        print(f"  error: {e}")
    return 1 if errors else 0


def syntax_check() -> int:
    out = ROOT / OUTPUT_DIR
    files = sorted(out.glob("funcs_*.c"))
    log_dir = ROOT / "build" / "syntax"
    log_dir.mkdir(parents=True, exist_ok=True)
    incs = f'/I "{ROOT / "lib/N64Recomp/include"}" /I "{ROOT / "include"}"'
    bat = log_dir / "check.bat"
    bat.write_text("@echo off\r\n" + f'call "{VCVARS}" >nul\r\n' + f'cd /d "{out}"\r\n' + "".join(
        f'clang-cl /nologo /Zs /TC {NOISE_FLAGS} {incs} {f.name} > "{log_dir / (f.stem + ".log")}" 2>&1\r\n'
        for f in files))
    subprocess.run(["cmd", "/c", str(bat)], capture_output=True, text=True)
    diags = []
    for f in files:
        diags += [f"{f.name}: {l.strip()}" for l in (log_dir / f"{f.stem}.log").read_text(errors="replace").splitlines() if l.strip()]
    print(f"syntax check: {len(files)} files, {len(diags)} diagnostic lines")
    for d in diags[:20]:
        print(f"  {d}")
    return 1 if diags else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--trace", action="store_true")
    ap.add_argument("--no-run", action="store_true")
    ap.add_argument("--no-check", action="store_true")
    args = ap.parse_args()
    if args.trace:
        # Trace/coverage builds get their own config and output directory, so the normal build's
        # RecompiledFuncs/ is untouched (CMake -DWG3D_TRACE=ON compiles RecompiledFuncsTrace/; chunk 4.2).
        global CONFIG, OUTPUT_DIR
        CONFIG = ROOT / "wg3d.us.trace.toml"
        OUTPUT_DIR = "RecompiledFuncsTrace"
    write_config(args.trace)
    print(f"wrote {CONFIG.name}")
    if args.no_run:
        return 0
    if run_recompiler() or write_decls():
        return 1
    if args.no_check or args.trace:  # trace builds need trace.h, which Phase 3 provides
        return 0
    return syntax_check()


if __name__ == "__main__":
    sys.exit(main())
